### PR TITLE
Fix path to cropper.js

### PR DESCRIPTION
**Pull request by nibbledeez**
Allows ability to click-drag to zoom on the graphs

Not sure this is the best way to fix this as it's probably an upstream issue but this corrects the path to cropper.js which then enables click and zoom on time ranges on the graph.

### CODE REVIEW

**Comment by sparklyballs** [comment]
can you change the sed line to 

`sed 's#src="/cropper/#/src="cropper/#' /etc/smokeping/basepage.html`

lot easier to read without all the escaped backslashes...

**Comment by nibbledeez** [comment]
Sure - sorry - tend to over-escape everything. Not sure how this works - are you able to pull my latest commit?

**Comment by sparklyballs** [comment]
jenkins retest this please

**Comment by sparklyballs** [comment]
my bad, i forgot to add the -i for sed in place...

i'll merge and re-edit on a new PR.

**Pull request merged**
