### PR TITLE
changed httpd.conf DocumentRoot to point to smokeping as the default Apache page.

### PR DESCRIPTION
**Pull request by icepic0**
This is the fix that I wrote Issue #16 (Request to have smokeping come up as the default web page #16) for.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by sparklyballs** [comment]
jenkins test this please

**Comment by timelf123** [comment]
Yes please

**Comment by j0nnymoe** [comment]
jenkins test this please

**Comment by sparklyballs** [comment]
PR #24 places smokeping.conf in /config/site-confs/ on the mounted volume of /config

this will allow customisations like this to be made by users rather than attempting a one size fits all approach

**Pull request closed without merging**
