### PR TITLE
Add instructions to reload the configuration

### LINKED ISSUE #131: Doc Request: add instructions on how to reload the configuration
What is the best way to reload the configuration after making changes to the /config/Probes (etc.) files? Just stop and start the Docker container? Or is there a more graceful way?

Put these instructions in the README.

### PR DESCRIPTION
**Pull request by DeflateAwning**
Fixes #131. Instructions came from [this comment in #131](https://github.com/linuxserver/docker-smokeping/issues/131#issuecomment-1804065686).

### CODE REVIEW

**Comment by DeflateAwning** [comment]
Don't merge quite yet; still figuring out the best way to do this actually. The way in this PR is sub-optimal.

**Comment by DeflateAwning** [comment]
Confirmed that this current method is good to merge to main/master! Hopefully somone can review it!

**Comment by thespad** [comment]
Please replace `$CID` with `smokeping` (you can leave the note about replacing it with the name of your container), because 90% of our users will both use the default name and blindly copy/paste whatever is written in the readme.

Otherwise I'm happy to merge it.

**Comment by DeflateAwning** [comment]
FIxed! Changed `$CID` to `smokeping`.

**Review by thespad — APPROVED** [review]

**Pull request merged**
