### PR TITLE
Allowing the use of a port other than 80 for host=network use

### PR DESCRIPTION
**Pull request by troykelly**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-smokeping/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Use of the environment variable `PORT` in place of hard-coded `80`

## Benefits of this PR and context:

This addresses a difficulty in configuring docker to support IPv6 which is mitigated by allowing the container host network access. When doing this - there is no way to control which port the httpd server is listening on.
By adding a `PORT` environment variable, the container can be given `network_mode: host`

## How Has This Been Tested?

Configured httpd.conf to use environment variable, set environment variable

### CODE REVIEW

**Comment by troykelly** [comment]
Anyone?

**Comment by troykelly** [comment]
Ping

**Comment by qingmuhy** [comment]
This function is what i want.

**Comment by troykelly** [comment]
> This function is what i want.

It's a very simple change - but I don't think this is maintained any more

**Comment by qingmuhy** [comment]
I built an image myself with your code and it's working fine. Thank you！！！

**Comment by troykelly** [comment]
In this case, changing the port is quite essential if you want to use IPv6 easily.
It's a very simple, non-breaking change that add's (needed) functionality while not changing the experience for anybody else wanting to use it out of the box.

**Comment by troykelly** [comment]
Still needed

**Comment by troykelly** [comment]
Still needed...

**Comment by ironicbadger** [comment]
Does an end user need to specify any extra env vars to utilize this? Beyond the code change is it worth a small doc update explaining the change and how to consume for users?

**Comment by troykelly** [comment]
@ironicbadger just the `PORT` environment variable.
Yes - a documentation update would be good - but no point, really, there's no interest in incorporating the change - so we use our own container now.

**Comment by drizuid** [comment]
out support is offered for running this in bridge mode. I do this, my ipv6 works fine. Will close as OP moved to a different container anyway.

**Pull request closed without merging**
