### PR TITLE
Add TCPPing as a default available probe

### PR DESCRIPTION
**Pull request by DeflateAwning**
Add "TCPPing" as a probe type to the default "Probes" config. 

This `tcpping` script is available by default during the Dockfile setup, so it makes sense that it is included as a standardly-available probe.

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-smokeping/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

* Added a new probe to the default "Probes" config file (which lives in `/data` after setup).

## Benefits of this PR and context:

* This new Probe can be used easily in the Targets config.

## How Has This Been Tested?

* Tested locally, using endpoints like Google.com and 1.1.1.1.

### CODE REVIEW

**Comment by DeflateAwning** [comment]
[](url)

**Comment by DeflateAwning** [comment]
Please merge this pull request!

**Comment by DeflateAwning** [comment]
TCPPing is useful for performing outgoing ping tests on networks that block UDP packets, or for pinging devices that don't respond to regular pings but do have open TCP ports. 

The benefit it provides is being able to ping TCP ports by default from within this system. It may require extra documentation, but the documentation is mostly already present.

**Comment by DeflateAwning** [comment]
Please complete this task

**Comment by DeflateAwning** [comment]
I still want this

**Comment by ironicbadger** [comment]
What extra documentation is required? Would you be so kind as to write it?

**Comment by DeflateAwning** [comment]
On second thought, I don't think there's any documentation that pertains to this strictly. Let me know if you can think of any! Otherwise, it should be good to merge.

**Comment by ironicbadger** [comment]
@aptalca @Roxedus are you comfortable with merging this? Looks ok to me.

**Comment by DeflateAwning** [comment]
Would be great if we could merge this soon! Thanks

**Review by aptalca — APPROVED** [review]

**Pull request merged**
