### PR TITLE
add python package

### PR DESCRIPTION
**Pull request by miikka75**
Having python in the smokeping image I can install 3rd party probe speedtest-cli:
```
curl -L -o /usr/local/bin/speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py && chmod a+x /usr/local/bin/speedtest-cli
curl -L -o /usr/share/perl5/vendor_perl/Smokeping/probes/speedtest.pm https://github.com/mad-ady/smokeping-speedtest/raw/master/speedtest.pm
```
**Edit:**
Smokeping needs to be patched also because it's too old:
`wget -q -O - https://github.com/oetiker/SmokePing/commit/60419834f224a0735094fd4ad0aac8eac3b1528.diff | patch -p1 /usr/share/perl5/vendor_perl/Smokeping.pm
`

### CODE REVIEW

**Comment by miikka75** [comment]
Any admins following this projects? Please review!

**Comment by thelamer** [comment]
@miikka75 since this was opened we rebased to alpine 3.9 running 2.7.3-r3 of smokeping. I tested the script and their are no other deps, thanks for the contribution, I just need to add the changes to the changelog.

**Comment by thelamer** [comment]
@miikka75 can you please check "Allow edits from maintainers" on this PR or add the following line to the readme-vars after pulling from current master:
```
  - { date: "27.02.19:", desc: "Add python for supporting scripts." }
```
under changelogs.

**Comment by thelamer** [comment]
closing due to lack of response

**Pull request closed without merging**
