### PR TITLE
updates to allow ssmtp to work out of the box

### PR DESCRIPTION
**Pull request by aboutte**
- rename to conf file so it is a little more clear
- link the ssmtp.conf into /etc/ssmtp/
- update `sendmail` command in pathnames so it utilizes ssmtp

Without these changes I was not able to the docker container to send email notifications.

### CODE REVIEW

**Comment by tobbenb** [comment]
You have to find another way to get the ssmtp in the /etc folder. Symlinking to a volume mount is not something we want. Symlinks inside the container is ok.

**Comment by aboutte** [comment]
@tobbenb is [this](https://github.com/linuxserver/docker-smokeping/pull/40/commits/c38f90ddcebe2d7151592935165eae4e962a5a60) better?

**Comment by tobbenb** [comment]
Jenkins test this please

**Comment by tobbenb** [comment]
Sorry. I didn't remember that I commented here.

**Comment by aboutte** [comment]
@tobbenb done

**Comment by IronicBadger** [comment]
LGTM

**Pull request merged**
